# Sample workflow for testing the trigger-workflow action, 
# not intended to be triggered manually.
name: Simple workflow with dispatch trigger

on:
  workflow_dispatch:
    inputs:
      string_parameter:
        description: 'Simple string parameter'
        default: 'String parameter'
        required: true
      id:
        description: 'run identifier'
        default: 'no-id'
        type: string
        required: false

jobs:
  id:
    name: Workflow ID ${{ github.event.inputs.id }}
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.id }}
        run: echo run identifier ${{ github.event.inputs.id }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo string parameter
        run: echo ${{ github.event.inputs.string_parameter }}
