# Test workflow for the trigger-workflow action.
# It requests and waits for the execution of the 'dispatch.yaml' workflow using the workflow_dispatch event.
name: Trigger Workflow

on: 
  push: 
    branches:
      - main
    paths:
      - 'trigger-workflow/**.*'
  pull_request:
    branches:
      - main
    paths:
      - 'trigger-workflow/**.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger workflow with dispatch event
        uses: ./trigger-workflow
        with:
          owner: nuxeo
          repo: ui-team-gh-actions
          branch-name: main
          access-token: ${{ secrets.ACCESS_TOKEN }}
          workflow-id: dispatch.yaml
          poll-interval: '1000'
          inputs: |
            string_parameter: 'Run triggered with workflow_dispatch event'
