# Test workflow for the trigger-workflow action.
# It requests and waits for the execution of the 'dispatch.yaml' workflow using the workflow_dispatch event.
name: Trigger Workflow

on: 
  push: 
    branches:
      - main
    paths:
      - 'trigger-workflow/**.*'
  pull_request:
    branches:
      - main
    paths:
      - 'trigger-workflow/**.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # This step will add an output named 'result'
      - name: Trigger workflow with dispatch event
        id: main
        uses: ./trigger-workflow
        with:
          owner: nuxeo
          repo: ui-team-gh-actions
          branch-name: WEBUI-784-webui-elements-preview
          access-token: ${{ secrets.ACCESS_TOKEN }}
          workflow-id: dispatch.yaml
          poll-interval: '1000'
          inputs: |
            string_parameter: 'Run triggered with workflow_dispatch event'

      # These steps print and assert the 'result' output from the 'id: main' step
      - name: Output workflow result
        run: |
          echo ${{ steps.main.outputs.message }}

      - name: Assert remote workflow result
        if: ${{ github.event_name == 'pull_request' && steps.main.outputs.message != 'The wf run was successful' }}
        run: |
          echo 'The output should be "The wf run was successful", but was ${{ steps.main.outputs.message }}'
          exit 1
